// Code generated by MockGen. DO NOT EDIT.
// Source: offset_store.go

// Package consumer is a generated GoMock package.
package consumer

import (
	context "context"
	reflect "reflect"

	primitive "github.com/apache/rocketmq-client-go/v2/primitive"
	gomock "github.com/golang/mock/gomock"
)

// MockOffsetStore is a mock of OffsetStore interface.
type MockOffsetStore struct {
	ctrl     *gomock.Controller
	recorder *MockOffsetStoreMockRecorder
}

// MockOffsetStoreMockRecorder is the mock recorder for MockOffsetStore.
type MockOffsetStoreMockRecorder struct {
	mock *MockOffsetStore
}

// NewMockOffsetStore creates a new mock instance.
func NewMockOffsetStore(ctrl *gomock.Controller) *MockOffsetStore {
	mock := &MockOffsetStore{ctrl: ctrl}
	mock.recorder = &MockOffsetStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOffsetStore) EXPECT() *MockOffsetStoreMockRecorder {
	return m.recorder
}

// getMQOffsetMap mocks base method.
func (m *MockOffsetStore) getMQOffsetMap(topic string) map[primitive.MessageQueue]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getMQOffsetMap", topic)
	ret0, _ := ret[0].(map[primitive.MessageQueue]int64)
	return ret0
}

// getMQOffsetMap indicates an expected call of getMQOffsetMap.
func (mr *MockOffsetStoreMockRecorder) getMQOffsetMap(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getMQOffsetMap", reflect.TypeOf((*MockOffsetStore)(nil).getMQOffsetMap), topic)
}

// persist mocks base method.
func (m *MockOffsetStore) persist(ctx context.Context, mqs []*primitive.MessageQueue) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "persist", ctx, mqs)
}

// persist indicates an expected call of persist.
func (mr *MockOffsetStoreMockRecorder) persist(ctx, mqs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "persist", reflect.TypeOf((*MockOffsetStore)(nil).persist), ctx, mqs)
}

// persistSync mocks base method.
func (m *MockOffsetStore) persistSync(ctx context.Context, mqs []*primitive.MessageQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "persistSync", ctx, mqs)
	ret0, _ := ret[0].(error)
	return ret0
}

// persistSync indicates an expected call of persistSync.
func (mr *MockOffsetStoreMockRecorder) persistSync(ctx, mqs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "persistSync", reflect.TypeOf((*MockOffsetStore)(nil).persistSync), ctx, mqs)
}

// read mocks base method.
func (m *MockOffsetStore) read(ctx context.Context, mq *primitive.MessageQueue, t readType) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "read", ctx, mq, t)
	ret0, _ := ret[0].(int64)
	return ret0
}

// read indicates an expected call of read.
func (mr *MockOffsetStoreMockRecorder) read(ctx, mq, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "read", reflect.TypeOf((*MockOffsetStore)(nil).read), ctx, mq, t)
}

// readWithException mocks base method.
func (m *MockOffsetStore) readWithException(ctx context.Context, mq *primitive.MessageQueue, t readType) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "readWithException", ctx, mq, t)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// readWithException indicates an expected call of readWithException.
func (mr *MockOffsetStoreMockRecorder) readWithException(ctx, mq, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "readWithException", reflect.TypeOf((*MockOffsetStore)(nil).readWithException), ctx, mq, t)
}

// remove mocks base method.
func (m *MockOffsetStore) remove(ctx context.Context, mq *primitive.MessageQueue) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "remove", ctx, mq)
}

// remove indicates an expected call of remove.
func (mr *MockOffsetStoreMockRecorder) remove(ctx, mq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "remove", reflect.TypeOf((*MockOffsetStore)(nil).remove), ctx, mq)
}

// update mocks base method.
func (m *MockOffsetStore) update(mq *primitive.MessageQueue, offset int64, increaseOnly bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "update", mq, offset, increaseOnly)
}

// update indicates an expected call of update.
func (mr *MockOffsetStoreMockRecorder) update(mq, offset, increaseOnly interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "update", reflect.TypeOf((*MockOffsetStore)(nil).update), mq, offset, increaseOnly)
}
